"""Add cascade option for User tokens

Revision ID: 1997dda4bccc
Revises: 2f35c9155b99
Create Date: 2023-02-10 08:15:33.783206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1997dda4bccc'
down_revision = '2f35c9155b99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_keys_user_id_fkey', 'user_keys', type_='foreignkey')
    op.create_foreign_key(None, 'user_keys', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_tokens_user_id_fkey', 'user_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'user_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tokens', type_='foreignkey')
    op.create_foreign_key('user_tokens_user_id_fkey', 'user_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_keys', type_='foreignkey')
    op.create_foreign_key('user_keys_user_id_fkey', 'user_keys', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
