"""Add ReadPostRequest model

Revision ID: 815c08907f63
Revises: 93b3e98a307c
Create Date: 2023-05-15 06:33:36.403350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815c08907f63'
down_revision = '93b3e98a307c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('read_post_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_read_post_request_id'), 'read_post_request', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_read_post_request_id'), table_name='read_post_request')
    op.drop_table('read_post_request')
    # ### end Alembic commands ###
